### ISSUE TITLE
Max Weight addition

### ISSUE THREAD

**Issue by R1Dev** [davidmchapman/3DContainerPacking#14]
Thanks very much for this code, that's nice.
Do you think this is possible to add (easily) maximum weight in a container in this algorithm?
Kind regards

**Comment by davidmchapman** [comment]
My plan is to leave the logic for this algorithm frozen so that it behaves as defined in the original paper. Perhaps a weight check could be added as a pre- or post-processing step in the client code? If the max weight is exceeded, then you could peel off items until the packing result meets your criteria. Would that work?
