### ISSUE TITLE
Help me understand 

### ISSUE THREAD

**Issue by angelorfontana** [davidmchapman/3DContainerPacking#16]
You could help me understand the logic I have read the master's work but I have difficulties with the language. I made changes to the system and I'm already handling pallet rotation control. but I still do not understand very well the strategy used to define which pallets and in what position they will be placed in the container. From what I understand the layers function determines the best configuration for positioning the layers. But if you can give me an aid in understanding it would be much easier. What exactly is a layer and how it is mounted.
Thanks.

**Comment by davidmchapman** [comment]
Hello! I can try to help, but I did not write this algorithm, so I probably can't explain it perfectly. I do know that the algorithm packs items into the container in layers, one layer at a time. The height of the tallest item in that layer defines the total height of that layer. When that layer is done, the ceiling of that layer becomes the imaginary glass floor of the next layer. There is a process it uses to decide what item it is going to choose to start the next layer with. The process keeps repeating until it can't pack any more.

There is a further optimization to fill in cavities in the current layer, if any such cavities are formed during the packing process for that layer. It's been a long time since I looked at it, so I can't remember the details about that very well. But just know that before it "closes" the currently layer it will try to fill in cavities in that layer if it can.

Does this overview help at all? If you have any other specific questions, I could dig into the code with you and we can try to work it out.

**Comment by tempyzero** [comment]
> You could help me understand the logic I have read the master's work but I have difficulties with the language. I made changes to the system and I'm already handling pallet rotation control. but I still do not understand very well the strategy used to define which pallets and in what position they will be placed in the container. From what I understand the layers function determines the best configuration for positioning the layers. But if you can give me an aid in understanding it would be much easier. What exactly is a layer and how it is mounted.
> Thanks.

Can you please Specify How did you manage to get Rotation Control on Items?
