### ISSUE TITLE
View Results Locally

### ISSUE THREAD

**Issue by FoxBatTango** [davidmchapman/3DContainerPacking#5]
Rather than sending requests via WebAPI in order to view the results. Do you have the codes so that it may be developed locally? Thank you

**Comment by davidmchapman** [comment]
If you are in Visual Studio, there are two ways you can do this in your solution. The first is to bring the packing service project into your solution and then make a project reference to it in the project you want to use it in. From there you can instantiate the service directly. The other option is to build the service dll and reference that from your project. Similar concept. Does that help or would you like to see an example?

**Comment by FoxBatTango** [comment]
Thank you for the reply. It would be preferable to build the service dll and reference that from my project. An example would be greatly appreciated.

**Comment by davidmchapman** [comment]
Basically what you need to do is open a solution that has the ContainerPacking project and then build that project. That will create a dll for the service in the bin directory of that project folder (somewhere on your hard drive). Find that dll and copy it to a place that makes more sense for bundling it into your project. Then, with your project open in VS, right click on your project in solution explorer and choose Add Reference. From there you want to browse to the location of the dll and select it. The dll is now referenced in your project and you can use the classes in its namespace. The container packing dll will show up in the references list of your project. In the properties of that reference, be sure to set Copy Local to true so that the dll is copied to the output directory when you build your project. Hopefully all that makes sense. If anything is unclear, you could probably Google some of those terms to find a more comprehensive how-to online.

**Comment by FoxBatTango** [comment]
Thank you!
